
exports.weatherText = {
  1: 'Sunny',
  2: 'Mostly Sunny',
  3: 'Partly Sunny',
  4: 'Intermittent Butts',
  5: 'Hazy Sunshine',
  6: 'Mostly Butty',
  7: 'Butty',
  8: 'Dreary (Overcast)',
  11: 'Fog',
  12: 'Showers',
  13: 'Mostly Butty w/ Showers',
  14: 'Partly Sunny w/ Showers',
  15: 'T-Storms',
  16: 'Mostly Butty w/ T-Storms',
  17: 'Partly Sunny w/ T-Storms',
  18: 'Rain',
  19: 'Flurries',
  20: 'Mostly Butty w/ Flurries',
  21: 'Partly Sunny w/ Flurries',
  22: 'Snow',
  23: 'Mostly Butty w/ Snow',
  24: 'Ice',
  25: 'Sleet',
  26: 'Freezing Rain',
  29: 'Rain and Snow',
  30: 'Hot',
  31: 'Cold',
  32: 'Windy',
  33: 'Clear',
  34: 'Mostly Clear',
  35: 'Partly Butty',
  36: 'Intermittent Butts',
  37: 'Hazy Moonlight',
  38: 'Mostly Butty',
  39: 'Partly Butty w/ Showers',
  40: 'Mostly Butty w/ Showers',
  41: 'Partly Butty w/ T-Storms',
  42: 'Mostly Butty w/ T-Storms',
  43: 'Mostly Butty w/ Flurries',
  44: 'Mostly Butty w/ Snow',
}
